name: CI

on:
  push:
    branches: [ main ]

jobs:
  gitpage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: build
        run: |
          npm ci
          npm run lint
          npx ng add angular-cli-ghpages --skip-confirmation
          npx ng build --base-href=/${{ github.event.repository.name }}/
      - name: commit and push
        run: |
          cd dist/dev-fest-2024/browser
          git init
          git config user.name  "build-ci"
          git config user.email "build-ci@github.com"
          git remote add secure-origin https://${{ secrets.GENERAL_CI }}@github.com/gdg-twhk/${{ github.event.repository.name }}
          git checkout -b gh-pages
          git add .
          git commit -m "gitpage by CI"
          git push --force secure-origin gh-pages
  firebase-hosting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: build
        run: |
          npm ci
          npm run lint
          npx ng add angular-cli-ghpages --skip-confirmation
          npx ng build --base-href=/2024/
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: "./"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "${{ secrets.PROJECT_ID }}"
          channelId: live
